accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^cargo-list/$', views.show_cargo_list, name='cargo'),
    url(r'user-page/$', views.user_page_view, name='user'),
    url('', views.logout_view, name='logout'),
]

cargos/urls.py
from django.conf.urls import url
from cargos import views

app_name = 'cargos'

urlpatterns = [
    url(r'^add/$', views.add_cargo, name='add'),
    url(r'^transfer/$', views.add_transfer, name='transfer'),
    url(r'^rent/$', views.rent, name='rent'),
    url(r'^root-tr/$', views.rootTr, name='root')
]

online_service/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'accounts/', include('accounts.urls')),
    url(r'cargos/', include('cargos.urls')),
    url('', views.index_view, name='index'),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect

from cargos.models import Сonveyor, Cargo, Transfer, Rents


def index_view(request):
    transport_list = Сonveyor.objects.count()
    cargo = Cargo.objects.count()
    cargo_transfers = Transfer.objects.count()
    services = Rents.objects.count()
    content = {
        'transport_list': transport_list,
        'cargo': cargo,
        'cargo_transfers': cargo_transfers,
        'services': services
    }
    return render(request, 'home/home.html', content)


def show_cargo_list(request):
    conveyor = Сonveyor.objects.all()
    return render(request, 'home/cargo-list.html', {'conveyor': conveyor})


def user_page_view(request):
    my_cargos = Cargo.objects.filter(cargo_owner=request.user)
    my_transfers = Transfer.objects.filter(user=request.user)
    rent = Rents.objects.filter(username=request.user)
    data = {
        'my_cargos': my_cargos,
        'my_transfers': my_transfers,
        'rent': rent
    }
    return render(request, 'user/user-page.html', data)


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:user')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('accounts:user')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('index')

accounts/templates/home/cargo-list.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Список доступных перевозчиков</title>

    <style>
        body{
    margin: 0;
    padding: 0;
    font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
}

header{
    width: 15%;
    height: 100vh;
    float: left;
    position: fixed;
}

ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  width: 15%;
  background-color: #f1f1f1;
  position: fixed;
  height: 100%;
  overflow: auto;
}

li a {
  display: block;
  color: #000;
  padding: 8px 16px;
  text-decoration: none;
}

li a.active {
  background-color: #36bd82;
  color: white;
}

li a:hover:not(.active) {
  background-color: #36bd82;
  color: white;
}

#content{
    width: 85%;
    float: right;
    padding-bottom: 25px;
}
        
#content h1{
    text-align: center;
}        

.container{
    width: 80%;
    margin: 0 auto;
}

table{
    width: 100%;
    border-collapse: collapse;
}

th{
    padding: 10px;
    color: #fff;
    background-color: #36304a;
}

td{
    padding: 15px;
    text-align: center;
    background-color: rgb(224, 239, 241);
}

    </style>

</head>
<body>

<header class="header">

<ul>
    <li><a href="{% url 'accounts:login' %}">Войти</a></li>
    <li><a href="{% url 'accounts:signup' %}">Регистрация</a></li>
    <li><a href="{% url 'accounts:cargo' %}">Список перевозчиков</a></li>
</ul>

</header>

<section id="content">

    <h1>Список перевозчиков</h1>

<div class="container">
    {% if conveyor.count > 0 %}
    <table>
    <tr>
        <th>№</th>
        <th>Название</th>
        <th>Страна регистрации</th>
        <th>Адрес</th>
        <th>Тип транспорта</th>
    </tr>
        {% for con in conveyor %}
        <tr>
            <td>{{ con.id }}</td>
            <td>{{ con.name }}</td>
            <td>{{ con.country }}</td>
            <td>{{ con.address }}</td>
            <td>{{ con.type_of_transport }}</td>
        </tr>
        {% endfor %}
    </table>
{% endif %}
</div>

</section>

</body>
</html>

accounts/templates/home/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Система грузоперевозок</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<header class="header">

<ul>
    <li><a href="{% url 'accounts:login' %}">Войти</a></li>
    <li><a href="{% url 'accounts:signup' %}">Регистрация</a></li>
    <li><a href="{% url 'accounts:cargo' %}">Список перевозчиков</a></li>
</ul>

</header>

<section id="content">

    <div class="main-image" style="background-image: url({% static 'images/truck-1030846_1280.jpg' %});"></div>

    <div class="title"><h1>Наши результаты</h1></div>

    <div class="service-list">

        <div class="container">

            <div class="block-services">

        <div class="service-list-item">
            <div class="img"><img src="{% static 'images/package.png' %}" alt="package"></div>
            <div class="desc"><p>Пользователи добавили в систему {{ cargo }} груз</p></div>
        </div>

         <div class="service-list-item">
            <div class="img"><img src="{% static 'images/weight.png' %}" alt="weight"></div>
            <div class="desc"><p>Пользователь может заказать перевозку</p></div>
        </div>

         <div class="service-list-item">
            <div class="img"><img src="{% static 'images/truck.png' %}" alt="truck"></div>
            <div class="desc"><p>На данный момент в базе {{ transport_list }} перевозчик</p></div>
        </div>

        <div class="service-list-item">
            <div class="img"><img src="{% static 'images/humans.png' %}" alt="humans"></div>
            <div class="desc"><p>Выбор наших пользователей</p></div>
        </div>

        <div class="service-list-item">
            <div class="img"><img src="{% static 'images/jeep.png' %}" alt="jeep"></div>
            <div class="desc"><p>Заказано перевозок: {{ cargo_transfers }}</p></div>
        </div>

         <div class="service-list-item">
            <div class="img"><img src="{% static 'images/car.png' %}" alt="car"></div>
            <div class="desc"><p>Услуг заказано: {{ services }}</p></div>
        </div>

        </div>

        </div>

    </div>

</section>

</body>
</html>