accounts/urls.py
from django.conf.urls import url
from accounts import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^cargo-list/$', views.show_cargo_list, name='cargo'),
    url(r'user-page/$', views.user_page_view, name='user'),
    url('', views.logout_view, name='logout'),
]

cargos/urls.py
from django.conf.urls import url
from cargos import views

app_name = 'cargos'

urlpatterns = [
    url(r'^add/$', views.add_cargo, name='add'),
    url(r'^transfer/$', views.add_transfer, name='transfer'),
    url(r'^rent/$', views.rent, name='rent'),
    url(r'^root-tr/$', views.rootTr, name='root')
]

online_service/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'accounts/', include('accounts.urls')),
    url(r'cargos/', include('cargos.urls')),
    url('', views.index_view, name='index'),
]

accounts/models.py
from django.db import models

# Create your models here.

cargos/models.py
from datetime import date, timezone

from django.db import models


class Сonveyor(models.Model):
    name = models.CharField(max_length=65, unique=True)
    country = models.CharField(max_length=25)
    address = models.CharField(max_length=50)
    type_of_transport = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Cargo(models.Model):
    cargo_owner = models.CharField(max_length=100)
    cargo_name = models.CharField(max_length=70)
    cargo_weight = models.IntegerField()
    cargo_move_to = models.CharField(max_length=100)
    cargo_move_from = models.CharField(max_length=100)

    def __str__(self):
        return self.cargo_name


class Transfer(models.Model):
    company_name = models.CharField(max_length=100)
    user = models.CharField(max_length=77)
    cargo = models.CharField(max_length=100)
    adr_from = models.CharField(max_length=200)
    adr_to = models.CharField(max_length=200)
    weight = models.IntegerField()
    shipment_date = models.DateTimeField(auto_now_add=False)
    discharge_date = models.DateTimeField(auto_now_add=False)
    comment_field = models.TextField()
    transporter_field = models.CharField(max_length=140, default='name')
    status = models.CharField(max_length=100, default='принято')
    price = models.IntegerField(default=34)
    car_number = models.CharField(max_length=15, default='-')
    driver_surname = models.CharField(max_length=123, default='-')

    def __str__(self):
        return self.company_name


class Auto(models.Model):
    car_owner = models.CharField(max_length=100)
    car_name = models.CharField(max_length=123)
    car_type = models.CharField(max_length=100)
    price_per_day = models.IntegerField()
    number = models.CharField(max_length=100)


class Rents(models.Model):
    username = models.CharField(max_length=70)
    mark = models.CharField(max_length=77)
    days = models.IntegerField()
    total_price = models.IntegerField()


class Roots(models.Model):
    root = models.CharField(max_length=200)
    distance = models.IntegerField()
    stops = models.IntegerField(default='2')


class RootTransfers(models.Model):
    usr = models.CharField(max_length=110)
    user_root = models.CharField(max_length=200)
    cargo = models.CharField(max_length=150)
    crg_weight = models.CharField(max_length=7)
    start = models.CharField(max_length=20)
    end = models.CharField(max_length=20)

cargos/forms.py
from django import forms
from .models import Cargo, Transfer, Rents, Roots, RootTransfers


class CargoForm(forms.ModelForm):
    class Meta:
        model = Cargo
        fields = [
            'cargo_owner',
            'cargo_name',
            'cargo_weight',
            'cargo_move_to',
            'cargo_move_from'
        ]
        labels = {
            'cargo_owner': 'Пользователь, который добавляет груз',
            'cargo_name': 'Наименование груза',
            'cargo_weight': 'Масса',
            'cargo_move_to': 'Куда',
            'cargo_move_from': 'Откуда'
        }


class TransferForm(forms.ModelForm):
    class Meta:
        model = Transfer
        fields = [
            'company_name',
            'user',
            'cargo',
            'adr_from',
            'adr_to',
            'weight',
            'shipment_date',
            'discharge_date',
            'comment_field'
        ]
        labels = {
            'company_name': 'Юридическое название заказчика',
            'user': 'Пользователь системы',
            'cargo': 'Груз',
            'adr_from': 'Место загрузки',
            'adr_to': 'Место разгрузки',
            'weight': 'Масса',
            'shipment_date': 'Дата загрузки',
            'discharge_date': 'Дата разгрузки',
            'comment_field': 'Дополнительный пожелания'
        }


class RentsForm(forms.ModelForm):
    class Meta:
        model = Rents
        fields = [
            'username',
            'mark',
            'days',
            'total_price'
        ]
        labels = {
            'username': 'Имя пользователя',
            'mark': 'Марка машины',
            'days': 'Количество дней',
            'total_price': 'Стоимость'
        }


class RootTrForm(forms.ModelForm):
    class Meta:
        model = RootTransfers
        fields = [
            'usr',
            'user_root',
            'cargo',
            'crg_weight',
            'start',
            'end'
        ]
        labels = {
            'usr': 'Имя пользователя',
            'user_root': 'Маршрут',
            'cargo': 'Груз',
            'crg_weight': 'Вес',
            'start': 'Загрузка',
            'end': 'Разрузка'
        }

accounts/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.shortcuts import render, redirect

from cargos.models import Сonveyor, Cargo, Transfer, Rents


def index_view(request):
    transport_list = Сonveyor.objects.count()
    cargo = Cargo.objects.count()
    cargo_transfers = Transfer.objects.count()
    services = Rents.objects.count()
    content = {
        'transport_list': transport_list,
        'cargo': cargo,
        'cargo_transfers': cargo_transfers,
        'services': services
    }
    return render(request, 'home/home.html', content)


def show_cargo_list(request):
    conveyor = Сonveyor.objects.all()
    return render(request, 'home/cargo-list.html', {'conveyor': conveyor})


def user_page_view(request):
    my_cargos = Cargo.objects.filter(cargo_owner=request.user)
    my_transfers = Transfer.objects.filter(user=request.user)
    rent = Rents.objects.filter(username=request.user)
    data = {
        'my_cargos': my_cargos,
        'my_transfers': my_transfers,
        'rent': rent
    }
    return render(request, 'user/user-page.html', data)


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:user')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('accounts:user')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('index')

cargos/views.py
from django.shortcuts import render
from cargos.forms import CargoForm, TransferForm, RentsForm, RootTrForm
from cargos.models import Auto, Roots


def add_cargo(request):
    form = CargoForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = CargoForm()

    context = {
        'form': form
    }
    return render(request, 'cargo/addcargo.html', context)


def add_transfer(request):
    form = TransferForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = TransferForm()

    content = {
        'form': form
    }
    return render(request, 'cargo/addtransfer.html', content)


def rent(request):
    form = RentsForm(request.POST or None)
    cars = Auto.objects.all()
    if form.is_valid():
        form.save()
        form = RentsForm()

    cont = {
        'form': form,
        'cars': cars
    }
    return render(request, 'cargo/service.html', cont)


def rootTr(request):
    form = RootTrForm(request.POST or None)
    roots = Roots.objects.all()
    if form.is_valid():
        form.save()
        form = RootTrForm

    content = {
        'form': form,
        'roots': roots
    }
    return render(request, 'cargo/root-transfer.html', content)

accounts/templates/cargo/addcargo.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Добавить груз</title>

    <style>

        form{
            width: 80%;
            margin: 0 auto;
        }

        input{
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
        }

        input[type=submit]{
            outline:none;
            height: 40px;
            text-align: center;
            width: 130px;
            border-radius:40px;
            background: #fff;
            border: 2px solid #36bd82;
            color: #36bd82;
            letter-spacing:1px;
        }

        form div{
            text-align: center;
        }

        input[type=submit]:hover{
            background-color: #36bd82;
            color: #fff;
            cursor: pointer;
        }

    </style>

</head>
<body>

<h1 style="text-align: center;">Добавить груз</h1>

<form method="post">

    {% csrf_token %}
    {{ form.as_p }}

    <div><input type="submit" value="Добавить"></div>



</form>
</body>
</html>

accounts/templates/cargo/addtransfer.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Заявка на грузоперевозку</title>

     <style>

        form{
            width: 80%;
            margin: 0 auto;
        }

        input{
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
        }

        input[type=submit]{
            outline:none;
            height: 40px;
            text-align: center;
            width: 130px;
            border-radius:40px;
            background: #fff;
            border: 2px solid #36bd82;
            color: #36bd82;
            letter-spacing:1px;
        }

        form div{
            text-align: center;
        }

        input[type=submit]:hover{
            background-color: #36bd82;
            color: #fff;
            cursor: pointer;
        }

    </style>

</head>
<body>

<h1 style="text-align: center;">Заказать перевозку</h1>

    <form method="post">

    {% csrf_token %}
    {{ form.as_p }}

        <div><input type="submit" value="Добавить"></div>

</form>
</body>
</html>

accounts/templates/cargo/root-transfer.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Перевозка по маршруту</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <style>
         body{
        margin: 0;
        padding: 0;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        background-color: #F3F3F3;
    }

         td:nth-child(1):hover{
             cursor: pointer;
             color: #36bd82;
         }

    form{
        width: 80%;
        margin: 0 auto;
        text-align: center;
    }

.container{
    width: 80%;
    margin: 0 auto;
}

table{
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 55px;
}

th{
    padding: 10px;
    color: #fff;
    background-color: #36304a;
}

td{
    padding: 15px;
    text-align: center;
    background-color: rgb(224, 239, 241);
}

input[type=text],input[type=number]{
    font-family: Oswald-Medium;
    font-size: 16px;
    color: #43383e;
    line-height: 1.2;
    margin: 0 auto;
    display: block;
    width: 50%;
    height: 62px;
    background: #fff;
    border: 0;
    border-radius: 31px;
    padding: 0 35px 0 35px;
    outline: none;
}

input[type=submit]{
            outline:none;
            height: 40px;
            text-align: center;
            width: 130px;
            border-radius:40px;
            background: #fff;
            border: 2px solid #36bd82;
            color: #36bd82;
            letter-spacing:1px;
            margin-bottom: 40px;
}

input[type=submit]:hover{
            background-color: #36bd82;
            color: #fff;
            cursor: pointer;
}
    </style>

</head>
<body>

<section id="show-root">

<div class="container">

        <table>
            <tr>
                <th>Путь</th>
                <th>Расстояние</th>
                <th>Количество остановок</th>
            </tr>
            {% for root in roots %}
            <tr>
                <td onclick="this.ccc = function () {
                let root = $(this).html();
                $('#id_user_root').val(root);
                }
                this.ccc()">{{ root.root }}</td>
                <td>{{ root.distance }}</td>
                <td>{{ root.stops }}</td>
            </tr>
            {% endfor %}
        </table>


</div>
</section>

<section id="content">

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Отправить">
    </form>

</section>

</body>
</html>

accounts/templates/cargo/service.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Заказ услуги</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>

<style>

    body{
        margin: 0;
        padding: 0;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        background-color: #F3F3F3;
    }

    form{
        display: none;
        width: 80%;
        margin: 0 auto;
        text-align: center;
    }

.container{
    width: 80%;
    margin: 0 auto;
}

table{
    width: 100%;
    border-collapse: collapse;
}

th{
    padding: 10px;
    color: #fff;
    background-color: #36304a;
}

td{
    padding: 15px;
    text-align: center;
    background-color: rgb(224, 239, 241);
}

    #cars{
        margin-bottom: 50px;
    }


input[type=text],input[type=number]{
    font-family: Oswald-Medium;
    font-size: 16px;
    color: #43383e;
    line-height: 1.2;
    margin: 0 auto;
    display: block;
    width: 50%;
    height: 62px;
    background: #fff;
    border: 0;
    border-radius: 31px;
    padding: 0 35px 0 35px;
    outline: none;
}


</style>

<body>

<section id="cars">

<div class="container">

    <table>
        <tr>
        <th>Владелец</th>
        <th>Марка</th>
        <th>Тип транспорта</th>
        <th>Номер</th>
        <th>Цена за день</th>
        <th>Заказ</th>
        </tr>
         {% for car in cars %}
              <tr id="choice">
             <td>{{ car.car_owner }}</td>
             <td id="choice-car" onclick="this.selectCar = function () {
                let a = $(this).html();
                $('#id_mark').val(a);
             }
             this.selectCar()">{{ car.car_name }}</td>
             <td>{{ car.car_type }}</td>
             <td>{{ car.number }}</td>
                  <td onclick="this.scount = function () {
                let price = $(this).html();
                $('#id_total_price').val(price);
                  }
                  this.scount()">{{ car.price_per_day }}</td>
             <td><button>Заказать</button></td>
             </tr>
         {% endfor %}
    </table>

</div>

</section>

<section id="content">
    <form method="post">
        
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
        
    </form>
</section>

<script>
    $('button').click(function () {
    $('form').css('display', 'block');
    })
</script>

</body>
</html>